services:
    ubuntu:
        image: ubuntu:latest
        env_file:
            - .env
        volumes:
            - /:/host
            - ./entrypoint.sh:/entrypoint.sh
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
        stdin_open: true
        tty: true
        entrypoint: ["/bin/bash", "/entrypoint.sh"]
